"""
论文发布模块
生成 Markdown 文件并维护索引
"""

from datetime import datetime
from pathlib import Path
from typing import Dict, List


def write_daily_md(
    papers: List[Dict],
    out_dir: str = "papers",
    date: str = None
) -> Path:
    """
    生成每日论文 Markdown 文件

    Args:
        papers: 带摘要的论文列表
        out_dir: 输出目录
        date: 指定日期 (YYYY-MM-DD)，默认今天

    Returns:
        生成的文件路径
    """
    today = date or datetime.now().strftime("%Y-%m-%d")
    year, month = today[:4], today[5:7]

    fp = Path(out_dir) / year / month / f"{today}.md"
    fp.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        f"# Daily Paper Radar \u2014 {today}",
        "",
        f"今日共筛出 **{len(papers)}** 篇相关论文",
        "",
        "| 字段 | 说明 |",
        "|------|------|",
        "| **评分** | 0-10 分，基于与 Ryan 研究方向的匹配度 |",
        "| **关键词** | 匹配到的检索关键词 |",
        "",
        "---",
        "",
    ]

    for i, p in enumerate(papers, 1):
        # 作者处理
        authors = p['authors'][:5]
        author_str = ', '.join(authors)
        if len(p['authors']) > 5:
            author_str += f" 等 {len(p['authors'])} 人"

        # 匹配的关键词
        keywords = ', '.join(p.get('matched_keywords', []))

        lines.extend([
            f"## {i}. {p['title']}",
            "",
            f"**作者**：{author_str}",
            f"**arXiv**：[{p['url']}]({p['url']})",
            f"**PDF**：[下载]({p['pdf']})",
            f"**类别**：{p.get('primary_category', 'N/A')}",
            f"**关键词匹配**：{keywords}",
            "",
            f"**相关性评分**：{p['score']}/10 \u2014 {p['reason']}",
            "",
            f"{p.get('summary', '摘要暂缺')}",
            "",
            "---",
            "",
        ])

    # 页脚
    lines.extend([
        "",
        f"*Generated by Paper Radar on {datetime.now().strftime('%Y-%m-%d %H:%M')}*",
    ])

    fp.write_text('\n'.join(lines), encoding='utf-8')
    print(f"[INFO] 已生成: {fp}")
    return fp


def update_index(out_dir: str = "papers") -> Path:
    """
    更新总索引文件 papers/README.md

    Args:
        out_dir: 论文输出目录

    Returns:
        索引文件路径
    """
    root = Path(out_dir)
    if not root.exists():
        root.mkdir(parents=True)

    # 收集所有论文文件（排除 README.md）
    files = sorted(root.rglob("*.md"), reverse=True)
    files = [f for f in files if f.name != "README.md"]

    # 按年/月分组
    grouped = {}
    for f in files:
        # 从路径提取日期: papers/2026/04/2026-04-25.md
        parts = f.relative_to(root).parts
        if len(parts) >= 3:
            year_month = f"{parts[0]}/{parts[1]}"
        else:
            year_month = "其他"

        if year_month not in grouped:
            grouped[year_month] = []
        grouped[year_month].append(f)

    # 生成索引内容
    lines = [
        "# Paper Radar Archive",
        "",
        "自动追踪 arXiv 上与 Ryan 研究方向相关的最新论文。",
        "",
        "## 最新更新",
        "",
    ]

    for ym in sorted(grouped.keys(), reverse=True):
        lines.append(f"### {ym}")
        lines.append("")
        for f in grouped[ym]:
            date = f.stem
            rel = f.relative_to(root)
            lines.append(f"- [{date}]({rel})")
        lines.append("")

    # 添加统计信息
    total = len(files)
    lines.extend([
        "---",
        "",
        f"**总计**: {total} 篇论文",
        "",
        "*本索引自动更新*",
    ])

    index_fp = root / "README.md"
    index_fp.write_text('\n'.join(lines), encoding='utf-8')
    print(f"[INFO] 已更新索引: {index_fp}")
    return index_fp


def write_deep_research(paper: Dict, content: str, out_dir: str = "papers") -> Path:
    """
    写入深度研究报告到单独目录

    Args:
        paper: 论文信息
        content: 深度分析内容
        out_dir: 输出目录

    Returns:
        文件路径
    """
    today = datetime.now().strftime("%Y-%m-%d")
    year, month = today[:4], today[5:7]

    deep_dir = Path(out_dir) / year / month / "deep"
    deep_dir.mkdir(parents=True, exist_ok=True)

    # 用论文标题的前几个单词作为文件名
    safe_title = paper['title'][:50].replace(' ', '_').replace('/', '_')
    fp = deep_dir / f"{today}_{safe_title}.md"

    lines = [
        f"# 深度笔记: {paper['title']}",
        "",
        f"**原文**: [{paper['url']}]({paper['url']})",
        f"**作者**: {', '.join(paper['authors'][:3])}",
        f"**日期**: {today}",
        "",
        "---",
        "",
        content,
    ]

    fp.write_text('\n'.join(lines), encoding='utf-8')
    print(f"[INFO] 深度笔记已保存: {fp}")
    return fp


def generate_notification_content(
    papers: List[Dict],
    date: str = None
) -> str:
    """
    生成推送通知内容（纯文本格式）

    Args:
        papers: 论文列表
        date: 日期

    Returns:
        通知文本
    """
    today = date or datetime.now().strftime("%Y-%m-%d")

    lines = [
        f"Paper Radar - {today}",
        f"今日共 {len(papers)} 篇相关论文",
        "",
    ]

    for i, p in enumerate(papers[:5], 1):  # 只显示前5篇
        lines.append(f"{i}. [{p['score']}分] {p['title']}")
        lines.append(f"   {p['url']}")
        lines.append("")

    return '\n'.join(lines)


if __name__ == "__main__":
    # 测试
    test_papers = [
        {
            'title': 'Test Paper on Federated Learning',
            'authors': ['Alice', 'Bob', 'Charlie'],
            'url': 'https://arxiv.org/abs/2401.00001',
            'pdf': 'https://arxiv.org/pdf/2401.00001.pdf',
            'primary_category': 'cs.LG',
            'matched_keywords': ['federated learning'],
            'score': 8,
            'reason': '高度相关',
            'summary': '**核心贡献**：提出了新的联邦学习方法...\n\n**技术方法**：使用...'
        }
    ]

    write_daily_md(test_papers)
    update_index()
